import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";

import Header from '../components/Header'
import Footer from '../components/Footer'

const mainFontFamily = Poppins({
  weight: ['100','200', '300' , '400', '500' , '600' , '700'],
  style: ["normal", "italic"],
  subsets:['latin']
})

export const metadata: Metadata = {
  title: "Humberto Galdino - Dev Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-Br">
      <body
        className={`${mainFontFamily.className} antialiased w-4/5 m-auto min-h-screen p-8`}
      >
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}
